In [2]:
import numpy as np

NumPy Arrays

In [3]:
arr = np.array([1,2,3,5])
arr

array([1, 2, 3, 5])

In [4]:
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [5]:
b = [1,2,3.5,"hello"]
np.array(b)

array(['1', '2', '3.5', 'hello'], dtype='<U32')

In [6]:
c = [1,2,3.5]
np.array(c)

array([1. , 2. , 3.5])

Vector and Matrix

In [7]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Array Generation

In [9]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr2 = np.arange(1,11,2)
arr2

array([1, 3, 5, 7, 9])

In [11]:
arr = np.zeros(9)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
arr = np.zeros((3,3))
arr 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Line Spacing

In [13]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [14]:
arr = np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [15]:
arr = np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [16]:
arr = np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

Random Generation Formula

In [17]:
np.random.rand(10)

array([0.85588485, 0.64266396, 0.07300842, 0.33917087, 0.83310398,
       0.00396934, 0.65663769, 0.98521937, 0.2588285 , 0.25521099])

In [18]:
np.random.randn(9)

array([ 0.67936216,  0.22936026,  0.55821239,  0.47830452,  0.7872978 ,
       -0.00237041,  0.59484857, -0.19123343,  0.10323225])

In [19]:
np.random.randint(9)

5

In [20]:
np.random.randint(1,20,10)

array([ 8,  1,  1, 17,  4, 18,  4,  1, 17,  9], dtype=int32)

Array Attributes

In [21]:
arr = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
arr.shape

(3, 3)

In [23]:
arr.size

9

In [24]:
arr.dtype

dtype('int64')

Array Methods

In [25]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(9)

In [28]:
arr.sum()

np.int64(45)

In [29]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [30]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [31]:
arr.mean()

np.float64(5.0)

In [34]:
arr.std()

np.float64(2.581988897471611)

In [35]:
arr.argmax()

np.int64(8)

In [36]:
arr.argmin()

np.int64(0)

Reshaping And Resizing

In [37]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [41]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])