NUMPY INDEXING AND SLICING OF VECTOR

In [3]:
import numpy as np

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
arr[1:5]

array([12, 13, 14, 15])

In [7]:
arr[:6]

array([11, 12, 13, 14, 15, 16])

In [8]:
arr[6:]

array([17, 18, 19, 20])

In [9]:
arr[1::2]

array([12, 14, 16, 18, 20])

NUMPY INDEXING AND SLICING OF MATRIX

In [11]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
arr[0]

array([1, 2, 3, 4, 5])

In [13]:
arr[1,3]

np.int64(9)

In [14]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [15]:
arr[:, 2]

array([ 3,  8, 13, 18, 23, 28])

BOOLEAN INDEXING

In [26]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [27]:
bool_index = arr % 2 == 0 
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [28]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])