In [1]:
import numpy as np

Array Operations

Arithmetic Operations 

Broadcasting 

Deep and shallow copy 

Metrics operations. 

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])  


In [7]:
C = A + B
C

array([[ 6,  8],
       [10, 12]])

In [ ]:
D = A * B # Element-wise multiplication
D

array([[ 5, 12],
       [21, 32]])

In [9]:
E = A @ B # Matrix multiplication   
E

array([[19, 22],
       [43, 50]])

In [ ]:
F = np.dot(A, B) # Another way to perform matrix multiplication
F

array([[19, 22],
       [43, 50]])

In [ ]:
A.T # Transpose of A

array([[1, 3],
       [2, 4]])

In [17]:
A

array([[1, 2],
       [3, 4]])

In [18]:
B

array([[5, 6],
       [7, 8]])

Advanced Array Manipulation 

Stacking Array

In [19]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [20]:
np.vstack((a, b)) # Vertical stacking

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [21]:
np.hstack((a, b)) # Horizontal stacking

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
np.column_stack((a, b)) # Column stacking

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

Splitting array 

In [24]:
c = np.arange(16).reshape((4, 4))
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
np.hsplit(c, 2) # Split c into 2 equal arrays horizontally

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [28]:
np.vsplit(c, 2) # Split c into 2 equal arrays vertically

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [27]:
for i in a:
    print(i)

1
2
3
4
